[profile.default]
src = 'src'
out = 'out'
libs = ["lib", "node_modules"]
optimizer = true
optimizer_runs = 1
solc = "0.8.19"
bytescode_hash = "none"
# viaIR = true
cache_path = 'forge-cache'
fs_permissions = [{ access = "read", path = "./" }]

allow_paths = [
    # pnpm symlinks to the project root's node_modules
    "../../node_modules",
]

# set debug when debug, set default to commit
revert_strings = "debug"
[invariant]

run = 1024
depth = 30
fail_on_revert = false

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[fuzz]
runs = 256
max_test_rejects = 65536