# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: on_pr

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      - run: npm run compile
      - run: npm run coverage
      - name: monitor coverage
        uses: slavcodev/coverage-monitor-action@1.5.0
        with:
          coverage_path: 'coverage/clover.xml'
          github_token: ${{ github.token }}
