# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Download compile manually
        id: download-solidity-compiler
        run: mkdir -p /home/runner/.cache/hardhat-nodejs/compilers-v2/linux-amd64/; wget https://github.com/ethereum/solidity/releases/download/v0.8.19/solc-static-linux -O /home/runner/.cache/hardhat-nodejs/compilers-v2/linux-amd64/solc-linux-amd64-v0.8.19+commit.7dd6d404; chmod 777 /home/runner/.cache/hardhat-nodejs/compilers-v2/linux-amd64/solc-linux-amd64-v0.8.19+commit.7dd6d404; wget https://binaries.soliditylang.org/linux-amd64/list.json -O /home/runner/.cache/hardhat-nodejs/compilers-v2/linux-amd64/list.json

      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      # - name: Setup upterm session
      #   uses: mxschmitt/action-tmate@v3
      #   # with:

      - run: pnpm compile
      - run: pnpm lint
      # - run: pnpm test

      - run: cd packages/dev;forge coverage --report lcov;

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
